# Generated by Django 4.0.6 on 2022-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_name', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
