# Generated by Django 4.0.6 on 2022-07-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0003_contestant_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conduct.contestant')),
            ],
        ),
    ]
