# Generated by Django 4.0.6 on 2022-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0006_remove_account_contestant_account_contestant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Prateek', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Jain', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(default='9818093423', max_length=100),
        ),
    ]
