# Generated by Django 4.0.6 on 2022-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0007_remove_account_name_remove_account_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(default='9818093423', max_length=100, unique=True),
        ),
    ]
