# Generated by Django 4.0.6 on 2022-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0009_contestant_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mobile',
        ),
        migrations.AddField(
            model_name='account',
            name='voter_class',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='6', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='voter_section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], default='A', max_length=10),
        ),
    ]
